
--DROP TABLE ZHEFSS_ACCT_INFO CASCADE CONSTRAINTS;
CREATE TABLE ZHEFSS_ACCT_INFO  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  FK_ID               VARCHAR2(32),
  BANK_ACCT_NO        VARCHAR2(50) NOT NULL ,
  BANK_NM             VARCHAR2(50),
  PROJECT_NAME        VARCHAR2(50),
  PRESALE_NUMBER      VARCHAR2(1000),
  BANKNUMBER          VARCHAR2(20),
  ACCOUNT_STATUS      VARCHAR2(1),
  MANAGE_STATUS       VARCHAR2(1),
  MONITOR_TIME        VARCHAR2(14),
  CHANGE_TIME         VARCHAR2(14),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_ACCT_INFO PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_ACCT_INFO IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.FK_ID IS '关联关系';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.BANK_ACCT_NO IS '银行账号';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.BANK_NM IS '银行名称';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.PRESALE_NUMBER IS '预售证编号';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.BANKNUMBER IS '银行统一编号';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.ACCOUNT_STATUS IS '监管状态  1-监管中 2-解除监管';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.MANAGE_STATUS IS '柜员确认状态 0-未确认（默认） 1-确然监管 2-确认撤销';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.MONITOR_TIME IS '监管时间';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.CHANGE_TIME IS '变更时间';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_ACCT_INFO.REQ_ID IS 'req_id';


create sequence SEQ_ZHEFSS_ACCT_INFO
minvalue 10000001
maxvalue 99999999
start with 10000001
increment by 1
cache 20;



--DROP TABLE ZHEFSS_TFR_INFO CASCADE CONSTRAINTS;
CREATE TABLE ZHEFSS_TFR_INFO  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  FK_ID               VARCHAR2(32),
  RV_TIME             VARCHAR2(18),
  IBS_FLOW            VARCHAR2(36),
  BANK_NUMBER         VARCHAR2(20),
  BANK_NM             VARCHAR2(50),
  ACOM_NAME           VARCHAR2(50),
  PROJECT_NAME        VARCHAR2(50),
  PRESALE_NUMBER      VARCHAR2(1000),
  MBANK_ACCOUNT       VARCHAR2(50),
  AMONEY              DECIMAL(18, 2),
  USEFOR              VARCHAR2(20),
  TRAN_BANK_NAME      VARCHAR2(50),
  TRAN_ACCT_NO        VARCHAR2(50),
  TRAN_ACCT_NAME      VARCHAR2(50),
  APPROVE_NUMBER      VARCHAR2(50),
  APPROVE_DATE        VARCHAR2(14),
  HB_FLOW             VARCHAR2(36),
  HB_TIME             VARCHAR2(18),
  RESP_CODE           VARCHAR2(20),
  RESP_MSG            VARCHAR2(256),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_TFR_INFO PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_TFR_INFO IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.FK_ID IS '关联主键';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RV_TIME IS '接收划拨指令时间';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.IBS_FLOW IS '接收划拨平台流水';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.BANK_NUMBER IS '银行统一编号';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.BANK_NM IS '银行名称';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.ACOM_NAME IS '申请企业名称';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.PRESALE_NUMBER IS '预售许可编号';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.MBANK_ACCOUNT IS '预售资金监管账号';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.AMONEY IS '申请拨付预售款金额';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.USEFOR IS '款项用途';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.TRAN_BANK_NAME IS '转账银行';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.TRAN_ACCT_NO IS '转账银行账号';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.TRAN_ACCT_NAME IS '转账账号名称';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.APPROVE_NUMBER IS '核准批复编号';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.APPROVE_DATE IS '核准批复时间';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.HB_FLOW IS '划拨平台流水';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.HB_TIME IS '划拨平台时间';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RESP_CODE IS '返回码';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RESP_MSG IS '结果信息';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_TFR_INFO.REQ_ID IS 'req_id';

create sequence SEQ_ZHEFSS_TFR_INFO
minvalue 10000001
maxvalue 99999999
start with 10000001
increment by 1
cache 20;



--drop table ZHEFSS_PROTECT_NOTIFY;
CREATE TABLE ZHEFSS_PROTECT_NOTIFY  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  APPLY_NUMBER        VARCHAR2(50) NOT NULL ,
  APPLY_NUMBER_END    VARCHAR2(50),
  FINISH_TIME_END     VARCHAR2(14),
  BANK_PROTECT_NUM    VARCHAR2(50),
  FINISH_TIME         VARCHAR2(14),
  COMPANY_NAME        VARCHAR2(50),
  CREDIT_LEVEL        VARCHAR2(1),
  PROJECT_NAME        VARCHAR2(50),
  PROJECT_ADDRESS     VARCHAR2(100),
  PRESALE_NUMBERS     VARCHAR2(1000),
  MANAGE_ACCOUNT_INFOS VARCHAR2(2000),
  PROTECT_MONEY       DECIMAL(18, 2),
  PROTECT_MONEY_CAPITAL VARCHAR2(100),
  STOP_REASON         VARCHAR2(500),
  GUARANTEE_BANK      VARCHAR2(100),
  AUDIT_STS           VARCHAR2(1),
  TXN_DT              VARCHAR2(8),
  TXN_TM              VARCHAR2(6),
  OPEN_STATUS         VARCHAR2(5),
  FAILREASON          VARCHAR2(1000),
  OPEN_DATE           VARCHAR2(14),
  VALID_DATE          VARCHAR2(14),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_PROTECT_NOTIFY PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_PROTECT_NOTIFY IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.APPLY_NUMBER IS '启用通知编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.APPLY_NUMBER_END IS '终止通知编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.FINISH_TIME_END IS '终止保函审核通过时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.BANK_PROTECT_NUM IS '保函编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.FINISH_TIME IS '启用保函审核通过时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.COMPANY_NAME IS '申请企业名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.CREDIT_LEVEL IS '信用等级';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PROJECT_ADDRESS IS '项目地址';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PRESALE_NUMBERS IS '预售证证号';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.MANAGE_ACCOUNT_INFOS IS '预售款专用账号';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PROTECT_MONEY IS '保函金额';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.PROTECT_MONEY_CAPITAL IS '保函金额大写';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.STOP_REASON IS '终止原因';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.GUARANTEE_BANK IS '保函出具银行';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.AUDIT_STS IS '审批状态 0：待审批 1：审批通过 2“审批不通过 3：无需审批';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.TXN_DT IS '审批日期';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.TXN_TM IS '审批时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.OPEN_STATUS IS '启用状态 yes-启用成功 no-启用失败';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.FAILREASON IS '启用失败原因';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.OPEN_DATE IS '保函开立时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.VALID_DATE IS '保函有效期';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_PROTECT_NOTIFY.REQ_ID IS 'req_id';

create sequence SEQ_ZHEFSS_PROTECT_NOTIFY
minvalue 10000001
maxvalue 99999999
start with 10000001
increment by 1
cache 20;


--drop table ZHEFSS_PROTECT_TFR_INFO;
CREATE TABLE ZHEFSS_PROTECT_TFR_INFO  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  APPROVE_NUMBER      VARCHAR2(50) NOT NULL ,
  FINISH_TIME         VARCHAR2(14),
  COMPANY_NAME        VARCHAR2(50),
  CREDIT_LEVEL        VARCHAR2(1),
  PROJECT_NAME        VARCHAR2(50),
  PROJECT_ADDRESS     VARCHAR2(100),
  PRESALE_NUMBERS     VARCHAR2(100),
  MANAGE_ACCOUNT_INFOS VARCHAR2(2000),
  BANK_PROTECT_NUM    VARCHAR2(50),
  VALID_DATE          VARCHAR2(14),
  PROTECT_MONEY       DECIMAL(18, 2),
  PROTECT_MONEY_CAPITAL VARCHAR2(100),
  GUARANTEE_BANK      VARCHAR2(100),
  BANK_ACCOUNT_NAME   VARCHAR2(100),
  BANK_ACCOUNT        VARCHAR2(100),
  BANK_NAME           VARCHAR2(100),
  BANK_NUM            VARCHAR2(100),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_PROTECT_TFR_INFO PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_PROTECT_TFR_INFO IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.APPROVE_NUMBER IS '拨付编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.FINISH_TIME IS '审核通过时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.COMPANY_NAME IS '申请企业名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.CREDIT_LEVEL IS '信用等级';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PROJECT_NAME IS '项目名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PROJECT_ADDRESS IS '项目地址';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PRESALE_NUMBERS IS '预售证证号';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.MANAGE_ACCOUNT_INFOS IS '监管账号信息';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.BANK_PROTECT_NUM IS '保函编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.VALID_DATE IS '保函有效期';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PROTECT_MONEY IS '拨付金额';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.PROTECT_MONEY_CAPITAL IS '拨付金额大写';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.GUARANTEE_BANK IS '保函出具银行';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.BANK_ACCOUNT_NAME IS '收款单位账户名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.BANK_ACCOUNT IS '收款单位账号';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.BANK_NAME IS '收款单位开户银行';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.BANK_NUM IS '收款行行号';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_PROTECT_TFR_INFO.REQ_ID IS 'req_id';

create sequence SEQ_ZHEFSS_PROTECT_TFR_INFO
minvalue 10000001
maxvalue 99999999
start with 10000001
increment by 1
cache 20;

--drop table ZHEFSS_PROTECT_CLAIM_ACCT_INFO;
CREATE TABLE ZHEFSS_PROTECT_CLAIM_ACCT_INFO  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  APPROVE_NUMBER      VARCHAR2(50) NOT NULL ,
  BANK_NAME_DETAIL    VARCHAR2(100),
  BANK_NAME           VARCHAR2(100),
  BANK_NUM            VARCHAR2(100),
  BANK_ACCOUNT_NAME   VARCHAR2(100),
  BANK_ACCOUNT        VARCHAR2(100),
  CLAIM_MONEY         DECIMAL(18, 2),
  CLAIM_MONEY_CAPITAL VARCHAR2(100),
  BANK_NUMBER         VARCHAR2(50),
  STS                 VARCHAR2(1),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_PROTECT_CLAIM_ACCT PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_PROTECT_CLAIM_ACCT_INFO IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.APPROVE_NUMBER IS '通知编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_NAME_DETAIL IS '开户行名称';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_NAME IS '开户行';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_NUM IS '行号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_ACCOUNT_NAME IS '账户名';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_ACCOUNT IS '账户号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.CLAIM_MONEY IS '索赔金额';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.CLAIM_MONEY_CAPITAL IS '索赔金额大写';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.BANK_NUMBER IS '核心流水号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.STS IS '确认状态 0-未确认 1-已确认';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_ACCT_INFO.REQ_ID IS 'req_id';



--drop table ZHEFSS_PROTECT_CLAIM_TFR_INFO;
CREATE TABLE ZHEFSS_PROTECT_CLAIM_TFR_INFO  (
  PK_ID               VARCHAR2(32) NOT NULL ,
  APPROVE_NUMBER      VARCHAR2(50) NOT NULL ,
  FINISH_TIME         VARCHAR2(14),
  BANK_PROTECT_NUM    VARCHAR2(50),
  DAMAGE_NAME         VARCHAR2(500),
  APPLYT_MONEY        DECIMAL(18, 2),
  APPLY_MONEY_CAPITAL VARCHAR2(100),
  END_TIME            VARCHAR2(14),
  CONFIRM_STS         VARCHAR2(1),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_PROTECT_CLAIM_TFR PRIMARY KEY (PK_ID)
)
;


COMMENT ON TABLE ZHEFSS_PROTECT_CLAIM_TFR_INFO IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.PK_ID IS '主键';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.APPROVE_NUMBER IS '通知编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.FINISH_TIME IS '审核通过时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.BANK_PROTECT_NUM IS '保函编号';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.DAMAGE_NAME IS '索赔事项';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.APPLYT_MONEY IS '总索赔金额';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.APPLY_MONEY_CAPITAL IS '总索赔金额大写';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.END_TIME IS '索赔截止时间';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.CONFIRM_STS IS '标记状态 0-待处理 1-处理中 2-已完成';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_PROTECT_CLAIM_TFR_INFO.REQ_ID IS 'req_id';

create sequence SEQ_ZHEFSS_PROTECT_CLAIM_TFR
minvalue 10000001
maxvalue 99999999
start with 10000001
increment by 1
cache 20;


--drop table ZHEFSS_ACCT_QRY_JNL;
CREATE TABLE ZHEFSS_ACCT_QRY_JNL  (
  JNL_NO              VARCHAR2(32) NOT NULL ,
  BANK_ACCT_NO        VARCHAR2(50),
  BANK_NM             VARCHAR2(50),
  BANK_ACCT_NM        VARCHAR2(50),
  REMAINDER_MONEY     DECIMAL(18, 2),
  ACCOUNT_STATE       VARCHAR2(1),
  REMARKS             VARCHAR2(300）,
  PRESALE_NUMBER      VARCHAR2(1000),
  BANKNUMBER          VARCHAR2(20),
  POST_TIME           VARCHAR2(14),
  TXN_DT              VARCHAR2(8),
  TXN_TM              VARCHAR2(6),
  RMK                 VARCHAR2(300),
  RSV1                VARCHAR2(300),
  RSV2                VARCHAR2(300),
  RSV3                VARCHAR2(300),
  RSV4                VARCHAR2(300),
  RSV5                VARCHAR2(300),
  NOD_ID              VARCHAR2(32),
  TM_SMP              VARCHAR2(14),
  REQ_ID              VARCHAR2(256),
  CONSTRAINT PK_ZHEFSS_ACCT_QRY_JNL PRIMARY KEY (JNL_NO)
)
;


COMMENT ON TABLE ZHEFSS_ACCT_QRY_JNL IS 'tabledesc';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.JNL_NO IS '交易流水号';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.BANK_ACCT_NO IS '银行账号';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.BANK_NM IS '银行名称';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.BANK_ACCT_NM IS '账号名称';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.REMAINDER_MONEY IS '账号余额';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.ACCOUNT_STATE IS '账号状态';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.REMARKS IS '账号状态说明';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.PRESALE_NUMBER IS '预售证编号';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.BANKNUMBER IS '银行统一编号';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.POST_TIME IS '查询时间';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.TXN_DT IS '交易日期';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.TXN_TM IS '交易时间';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RMK IS '备注';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RSV1 IS '备用字段1';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RSV2 IS '备用字段2';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RSV3 IS '备用字段3';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RSV4 IS '备用字段4';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.RSV5 IS '备用字段5';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.NOD_ID IS '节点ID';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.TM_SMP IS '时间戳';
COMMENT ON COLUMN ZHEFSS_ACCT_QRY_JNL.REQ_ID IS 'req_id';
